# Generated by Django 3.2.5 on 2024-12-11 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20241210_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='puplished_at',
            new_name='published_at',
        ),
    ]
